#!/bin/bash


############################################################################################
#CREATING FILE 

echo "Enter file name to make: "
read file

gedit $file


############################################################################################
#REMOVING FILE


echo "Do you want to remove file, press y for yes and n for no: "
read ch

ar="y"


if [ "$ch" \= "$ar" ]
then 
  echo "Enter the name of file to remove: "
  read file1
  
  if [ -f "$file1" ]
  then
     rm $file1
  else
    echo "File not found."
  fi
else
  echo "Ok no problem."
fi

